steps:

  # Step 1: Check if the code can be compiled
  - name: 'python:3.9' 
    entrypoint: 'python'
    args:
      - '-m'
      - 'py_compile'
      - 'dag.py'

  # Step 2: Optional - Try to run the code
  - name: 'python:3.9'  
    entrypoint: 'sh'
    args:
      - '-c'
      - | 
        python -m pip install -r requirements.txt
        python dag.py

  # Step 3: Copy file to DAG bucket
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        if [ "$BRANCH_NAME" = "main" ]; then
          ${_FILE_NAME}="main.py";
        elif [ "$BRANCH_NAME" = "dev" ]; then
          ${_FILE_NAME}="dev.py";
        else
          echo "Branch not recognized. Exiting.";
          exit 1;
        fi
        echo "Uploading dag.py as ${_FILE_NAME}";
        gcloud storage cp dag.py gs://us-central1-naya-8dbd1d56-bucket/dags/${_FILE_NAME}

substitutions:
  _FILE_NAME: "dag.py"

options:
  logging: CLOUD_LOGGING_ONLY
