steps:

  # Check if the code can be compiled
  - name: 'python:3.9' 
    entrypoint: 'python'
    args:
      - '-m'
      - 'py_compile'
      - 'dag.py'

  # Optional - try to run the code
  - name: 'python:3.9'  
    entrypoint: 'sh'
    args:
      - '-c'
      - | 
        python -m pip install -r requirements.txt
        python dag.py


  # Copy file to DAG bucket
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        if [ "$BRANCH_NAME" = "main" ]; then
          FILE_NAME="main.py";
        elif [ "$BRANCH_NAME" = "dev" ]; then
          FILE_NAME="dev.py";
        else
          echo "Branch not recognized. Exiting.";
          exit 1;
        fi
        echo "Uploading $FILE_NAME";
        gcloud storage cp dag.py gs://us-central1-naya-8dbd1d56-bucket/dags/$FILE_NAME

options:
  logging: CLOUD_LOGGING_ONLY
