steps:

  - name: 'python:3.9'  
    entrypoint: 'python'
    args:
      - '-m'
      - 'py_compile'
      - 'dag.py' 

  # Copy file to DAG bucket
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'storage'
      - 'cp'
      - 'dag.py'
      - 'gs://us-central1-naya-8dbd1d56-bucket/dags/dag.py'


options:
  logging: CLOUD_LOGGING_ONLY